/**
 * DEV DOC
 * Module: schemas/02-inventory/event-bookings.ts
 * Description: EventBookings Schema
 * Table: event_bookings
 * Category: 02-inventory
 * Primary exports: EventBookingsSchema, CreateEventBookingsSchema, UpdateEventBookingsSchema
 * @table event_bookings
 * @category 02-inventory
 * Ownership: Schema package
 */

/**
 * EventBookings Schema
 * @table event_bookings
 * @category 02-inventory
 * @synchronized 2025-11-14
 */

import { z } from 'zod';

import {
  uuid,
  money
} from '../../shared/base-schemas.js';

/**
 * Complete EventBookings schema
 */
export const EventBookingsSchema = z.object({
  event_id: uuid,
  tenant_id: uuid,
  property_id: uuid,
  event_number: z.string().optional(),
  event_name: z.string(),
  event_type: z.string(),
  meeting_room_id: uuid,
  event_date: z.coerce.date(),
  start_time: z.string(),
  end_time: z.string(),
  setup_start_time: z.string().optional(),
  actual_start_time: z.string().optional(),
  actual_end_time: z.string().optional(),
  teardown_end_time: z.string().optional(),
  organizer_name: z.string(),
  organizer_company: z.string().optional(),
  organizer_email: z.string().optional(),
  organizer_phone: z.string().optional(),
  contact_person: z.string().optional(),
  contact_email: z.string().optional(),
  contact_phone: z.string().optional(),
  contact_address: z.string().optional(),
  guest_id: uuid.optional(),
  reservation_id: uuid.optional(),
  company_id: uuid.optional(),
  group_booking_id: uuid.optional(),
  sales_lead_id: uuid.optional(),
  banquet_event_order_id: uuid.optional(),
  parent_booking_id: uuid.optional(),
  referral_source_id: uuid.optional(),
  assigned_event_planner_id: uuid.optional(),
  expected_attendees: z.number().int(),
  confirmed_attendees: z.number().int().optional(),
  actual_attendees: z.number().int().optional(),
  guarantee_number: z.number().int().optional(),
  max_capacity: z.number().int().optional(),
  vip_guest_count: z.number().int().optional(),
  attendee_demographics: z.record(z.unknown()).optional(),
  setup_type: z.string(),
  setup_details: z.string().optional(),
  special_requests: z.string().optional(),
  setup_diagram_url: z.string().optional(),
  signage_requirements: z.string().optional(),
  accessibility_requirements: z.string().optional(),
  decoration_details: z.string().optional(),
  theme: z.string().optional(),
  color_scheme: z.string().optional(),
  floral_arrangements: z.string().optional(),
  audio_visual_needed: z.boolean().optional(),
  lighting_requirements: z.string().optional(),
  stage_requirements: z.string().optional(),
  podium_required: z.boolean().optional(),
  microphone_count: z.number().int().optional(),
  internet_access_required: z.boolean().optional(),
  bandwidth_requirements: z.string().optional(),
  networking_requirements: z.string().optional(),
  recording_required: z.boolean().optional(),
  live_streaming_required: z.boolean().optional(),
  photographer_required: z.boolean().optional(),
  videographer_required: z.boolean().optional(),
  signage_url: z.string().optional(),
  irst_affiliate_marketing: z.boolean().optional(),
  social_media_integration: z.boolean().optional(),
  event_app_required: z.boolean().optional(),
  qr_code_integration: z.boolean().optional(),
  mobile_checkin_required: z.boolean().optional(),
  badge_printing_required: z.boolean().optional(),
  transportation_arrangements: z.string().optional(),
  parking_requirements: z.string().optional(),
  security_requirements: z.string().optional(),
  emergency_plan_details: z.string().optional(),
  required_equipment: z.record(z.unknown()).optional(),
  av_requirements: z.record(z.unknown()).optional(),
  technical_contact_name: z.string().optional(),
  technical_contact_email: z.string().optional(),
  technical_contact_phone: z.string().optional(),
  rehearsal_date: z.coerce.date().optional(),
  rehearsal_start_time: z.string().optional(),
  rehearsal_end_time: z.string().optional(),
  sound_check_required: z.boolean().optional(),
  lighting_check_required: z.boolean().optional(),
  av_setup_time: z.string().optional(),
  av_teardown_time: z.string().optional(),
  presentation_materials_required: z.boolean().optional(),
  webcast_required: z.boolean().optional(),
  simultaneous_translation_required: z.boolean().optional(),
  interpretation_services_required: z.boolean().optional(),
  equipment_rental_details: z.string().optional(),
  room_visualization_3d_url: z.string().optional(),
  agenda_details: z.string().optional(),
  speaker_list: z.record(z.unknown()).optional(),
  session_details: z.record(z.unknown()).optional(),
  breakout_room_requirements: z.record(z.unknown()).optional(),
  workshop_requirements: z.record(z.unknown()).optional(),
  panel_discussion_details: z.string().optional(),
  entertainment_details: z.string().optional(),
  awards_ceremony_details: z.string().optional(),
  keynote_speaker: z.string().optional(),
  opening_remarks_by: z.string().optional(),
  closing_remarks_by: z.string().optional(),
  networking_event_details: z.string().optional(),
  catering_required: z.boolean().optional(),
  catering_service_type: z.string().optional(),
  food_beverage_minimum: money.optional(),
  menu_selections: z.record(z.unknown()).optional(),
  dietary_restrictions: z.string().optional(),
  bar_service_required: z.boolean().optional(),
  alcohol_permit_required: z.boolean().optional(),
  catering_contact_name: z.string().optional(),
  catering_contact_email: z.string().optional(),
  catering_contact_phone: z.string().optional(),
  booking_status: z.string(),
  confirmation_status: z.string().optional(),
  payment_status: z.string().optional(),
  booked_date: z.coerce.date(),
  confirmed_date: z.coerce.date().optional(),
  beo_due_date: z.coerce.date().optional(),
  final_count_due_date: z.coerce.date().optional(),
  cancellation_deadline: z.coerce.date().optional(),
  decision_date: z.coerce.date().optional(),
  last_modified_date: z.coerce.date().optional(),
  event_completion_date: z.coerce.date().optional(),
  cancellation_date: z.coerce.date().optional(),
  no_show_date: z.coerce.date().optional(),
  reschedule_date: z.coerce.date().optional(),
  reminder_sent_date: z.coerce.date().optional(),
  followup_date: z.coerce.date().optional(),
  survey_sent_date: z.coerce.date().optional(),
  survey_completed_date: z.coerce.date().optional(),
  feedback_received_date: z.coerce.date().optional(),
  invoice_sent_date: z.coerce.date().optional(),
  payment_received_date: z.coerce.date().optional(),
  deposit_received_date: z.coerce.date().optional(),
  final_payment_date: z.coerce.date().optional(),
  event_planner_assigned_date: z.coerce.date().optional(),
  setup_completed_date: z.coerce.date().optional(),
  teardown_completed_date: z.coerce.date().optional(),
  equipment_setup_date: z.coerce.date().optional(),
  equipment_teardown_date: z.coerce.date().optional(),
  rehearsal_completed_date: z.coerce.date().optional(),
  catering_confirmed_date: z.coerce.date().optional(),
  av_confirmed_date: z.coerce.date().optional(),
  security_confirmed_date: z.coerce.date().optional(),
  transportation_confirmed_date: z.coerce.date().optional(),
  parking_confirmed_date: z.coerce.date().optional(),
  decoration_completed_date: z.coerce.date().optional(),
  signage_completed_date: z.coerce.date().optional(),
  marketing_materials_sent_date: z.coerce.date().optional(),
  social_media_posts_scheduled_date: z.coerce.date().optional(),
  event_app_launched_date: z.coerce.date().optional(),
  qr_codes_generated_date: z.coerce.date().optional(),
  mobile_checkin_setup_date: z.coerce.date().optional(),
  badge_printing_completed_date: z.coerce.date().optional(),
  rental_rate: money.optional(),
  setup_fee: money.optional(),
  equipment_rental_fee: money.optional(),
  av_equipment_fee: money.optional(),
  labor_charges: money.optional(),
  service_charge_percent: money.optional(),
  tax_rate: money.optional(),
  estimated_food_beverage: money.optional(),
  estimated_total: money.optional(),
  actual_total: money.optional(),
  currency_code: z.string().optional(),
  discount_amount: money.optional(),
  cancellation_fee: money.optional(),
  no_show_fee: money.optional(),
  tax_exempt: z.boolean().optional(),
  tax_exempt_certificate_url: z.string().optional(),
  deposit_required: money.optional(),
  deposit_paid: money.optional(),
  deposit_due_date: z.coerce.date().optional(),
  final_payment_amount: money.optional(),
  final_payment_due: z.coerce.date().optional(),
  payment_terms: z.string().optional(),
  refund_policy: z.string().optional(),
  invoice_number: z.string().optional(),
  receipt_number: z.string().optional(),
  contract_signed: z.boolean().optional(),
  contract_signed_date: z.coerce.date().optional(),
  contract_url: z.string().optional(),
  beo_pdf_url: z.string().optional(),
  floor_plan_url: z.string().optional(),
  seating_chart_url: z.string().optional(),
  menu_pdf_url: z.string().optional(),
  av_requirements_pdf_url: z.string().optional(),
  catering_agreement_url: z.string().optional(),
  insurance_certificate_url: z.string().optional(),
  permits_obtained: z.string().optional(),
  health_safety_measures: z.string().optional(),
  covid19_guidelines: z.string().optional(),
  emergency_contact_name: z.string().optional(),
  emergency_contact_phone: z.string().optional(),
  emergency_contact_email: z.string().optional(),
  evacuation_plan_url: z.string().optional(),
  folio_id: uuid.optional(),
  billing_instructions: z.string().optional(),
  billing_contact_name: z.string().optional(),
  billing_contact_email: z.string().optional(),
  payment_method: z.string().optional(),
  card_on_file: z.boolean().optional(),
  last_four_card_digits: z.string().optional(),
  billing_address: z.string().optional(),
  tax_identification_number: z.string().optional(),
  purchase_order_number: z.string().optional(),
  billing_cycle: z.string().optional(),
  ird_number: z.string().optional(),
  vat_number: z.string().optional(),
  gst_number: z.string().optional(),
  sst_number: z.string().optional(),
  withholding_tax_rate: money.optional(),
  event_planner_id: uuid.optional(),
  catering_manager_id: uuid.optional(),
  av_coordinator_id: uuid.optional(),
  setup_crew_lead_id: uuid.optional(),
  teardown_crew_lead_id: uuid.optional(),
  security_manager_id: uuid.optional(),
  cleaning_crew_lead_id: uuid.optional(),
  technical_support_id: uuid.optional(),
  staffing_requirements: z.record(z.unknown()).optional(),
  event_staffing_details: z.record(z.unknown()).optional(),
  volunteer_coordinator_id: uuid.optional(),
  volunteer_requirements: z.record(z.unknown()).optional(),
  staffing_schedule: z.record(z.unknown()).optional(),
  booking_source: z.string().optional(),
  lead_source: z.string().optional(),
  sales_manager_id: uuid.optional(),
  commission_rate: money.optional(),
  promotional_code: z.string().optional(),
  affiliate_partner_id: uuid.optional(),
  marketing_campaign_id: uuid.optional(),
  advertising_channel: z.string().optional(),
  social_media_platforms: z.record(z.unknown()).optional(),
  email_marketing_list_id: uuid.optional(),
  referral_contact_name: z.string().optional(),
  referral_contact_email: z.string().optional(),
  referral_contact_phone: z.string().optional(),
  customer_loyalty_id: uuid.optional(),
  discount_code_used: z.string().optional(),
  special_offers_applied: z.string().optional(),
  attendee_satisfaction_score: money.optional(),
  net_promoter_score: z.number().int().optional(),
  repeat_booking_likelihood: money.optional(),
  social_media_mentions: z.number().int().optional(),
  survey_response_rate: money.optional(),
  average_dwell_time_minutes: z.number().int().optional(),
  conversion_rate: money.optional(),
  revenue_per_attendee: money.optional(),
  cost_per_attendee: money.optional(),
  profit_margin_percent: money.optional(),
  event_rating: z.string().optional(),
  lessons_learned: z.string().optional(),
  improvement_areas: z.string().optional(),
  success_stories: z.string().optional(),
  challenges_faced: z.string().optional(),
  key_performance_indicators: z.record(z.unknown()).optional(),
  post_event_feedback: z.string().optional(),
  post_event_rating: z.number().int().optional(),
  issues_reported: z.string().optional(),
  followup_required: z.boolean().optional(),
  followup_actions: z.string().optional(),
  survey_results: z.record(z.unknown()).optional(),
  testimonials_collected: z.string().optional(),
  case_study_created: z.boolean().optional(),
  media_coverage_details: z.string().optional(),
  post_event_photos_url: z.string().optional(),
  post_event_videos_url: z.string().optional(),
  is_recurring: z.boolean().optional(),
  recurring_pattern: z.string().optional(),
  parent_event_id: uuid.optional(),
  series_id: uuid.optional(),
  security_required: z.boolean().optional(),
  insurance_required: z.boolean().optional(),
  liability_waiver_signed: z.boolean().optional(),
  internal_notes: z.string().optional(),
  public_notes: z.string().optional(),
  setup_notes: z.string().optional(),
  billing_notes: z.string().optional(),
  cancellation_notes: z.string().optional(),
  feedback_notes: z.string().optional(),
  special_instructions: z.string().optional(),
  additional_requirements: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date().optional(),
  created_by: uuid.optional(),
  updated_by: uuid.optional(),
  confirmed_by: uuid.optional(),
  is_deleted: z.boolean().optional(),
  deleted_at: z.coerce.date().optional(),
  deleted_by: uuid.optional(),
  version: z.bigint().optional(),
});

export type EventBookings = z.infer<typeof EventBookingsSchema>;

/**
 * Schema for creating a new event bookings
 */
export const CreateEventBookingsSchema = EventBookingsSchema.omit({
  // TODO: Add fields to omit for creation
});

export type CreateEventBookings = z.infer<typeof CreateEventBookingsSchema>;

/**
 * Schema for updating a event bookings
 */
export const UpdateEventBookingsSchema = EventBookingsSchema.partial();

export type UpdateEventBookings = z.infer<typeof UpdateEventBookingsSchema>;
