/**
 * MeetingRooms Schema
 * @table meeting_rooms
 * @category 02-inventory
 * @synchronized 2025-11-14
 */

import { z } from 'zod';
import {
  uuid,
  money
} from '../../shared/base-schemas.js';

/**
 * Complete MeetingRooms schema
 */
export const MeetingRoomsSchema = z.object({
  room_id: uuid,
  tenant_id: uuid,
  property_id: uuid,
  room_code: z.string(),
  room_name: z.string(),
  room_type: z.string(),
  building: z.string().optional(),
  floor: z.number().int().optional(),
  location_description: z.string().optional(),
  max_capacity: z.number().int(),
  theater_capacity: z.number().int().optional(),
  classroom_capacity: z.number().int().optional(),
  banquet_capacity: z.number().int().optional(),
  reception_capacity: z.number().int().optional(),
  u_shape_capacity: z.number().int().optional(),
  hollow_square_capacity: z.number().int().optional(),
  boardroom_capacity: z.number().int().optional(),
  area_sqm: money.optional(),
  area_sqft: money.optional(),
  length_meters: money.optional(),
  width_meters: money.optional(),
  height_meters: money.optional(),
  ceiling_height_meters: money.optional(),
  length_feet: money.optional(),
  width_feet: money.optional(),
  height_feet: money.optional(),
  ceiling_height_feet: money.optional(),
  has_natural_light: z.boolean().optional(),
  has_windows: z.boolean().optional(),
  has_stage: z.boolean().optional(),
  has_dance_floor: z.boolean().optional(),
  has_audio_visual: z.boolean().optional(),
  has_projector: z.boolean().optional(),
  has_screen: z.boolean().optional(),
  has_microphones: z.boolean().optional(),
  has_sound_system: z.boolean().optional(),
  has_wifi: z.boolean().optional(),
  has_video_conferencing: z.boolean().optional(),
  has_whiteboard: z.boolean().optional(),
  has_flipchart: z.boolean().optional(),
  has_podium: z.boolean().optional(),
  has_climate_control: z.boolean().optional(),
  has_lighting_control: z.boolean().optional(),
  has_soundproofing: z.boolean().optional(),
  has_stage_lighting: z.boolean().optional(),
  has_acoustic_treatment: z.boolean().optional(),
  has_video_wall: z.boolean().optional(),
  has_intercom_system: z.boolean().optional(),
  has_hearing_assistance: z.boolean().optional(),
  has_signage: z.boolean().optional(),
  has_refreshment_station: z.boolean().optional(),
  has_coat_check: z.boolean().optional(),
  has_restrooms: z.boolean().optional(),
  has_kitchenette: z.boolean().optional(),
  has_bar_area: z.boolean().optional(),
  has_outdoor_access: z.boolean().optional(),
  has_balcony: z.boolean().optional(),
  has_fireplace: z.boolean().optional(),
  has_artwork: z.boolean().optional(),
  has_plants: z.boolean().optional(),
  has_acoustic_ceiling: z.boolean().optional(),
  has_smart_controls: z.boolean().optional(),
  has_energy_efficient_lighting: z.boolean().optional(),
  has_recycling_bins: z.boolean().optional(),
  has_air_purification: z.boolean().optional(),
  has_solar_panels: z.boolean().optional(),
  has_green_certification: z.boolean().optional(),
  has_sound_masking: z.boolean().optional(),
  has_touchless_features: z.boolean().optional(),
  wheelchair_accessible: z.boolean().optional(),
  loading_dock_dimensions: z.string().optional(),
  has_loading_dock: z.boolean().optional(),
  has_separate_entrance: z.boolean().optional(),
  has_service_elevator: z.boolean().optional(),
  parking_spaces: z.number().int().optional(),
  elevator_access: z.boolean().optional(),
  default_setup: z.string().optional(),
  setup_time_minutes: z.number().int().optional(),
  teardown_time_minutes: z.number().int().optional(),
  turnover_time_minutes: z.number().int().optional(),
  hourly_rate: money.optional(),
  half_day_rate: money.optional(),
  full_day_rate: money.optional(),
  minimum_rental_hours: z.number().int().optional(),
  overtime_rate_per_hour: money.optional(),
  currency_code: z.string().optional(),
  operating_hours_start: z.string().optional(),
  operating_hours_end: z.string().optional(),
  available_days: z.array(z.string()).optional(),
  blackout_dates: z.array(z.coerce.date()).optional(),
  room_status: z.string(),
  is_active: z.boolean().optional(),
  included_equipment: z.record(z.unknown()).optional(),
  available_equipment: z.record(z.unknown()).optional(),
  furniture_inventory: z.record(z.unknown()).optional(),
  av_inventory: z.record(z.unknown()).optional(),
  decor_inventory: z.record(z.unknown()).optional(),
  lighting_inventory: z.record(z.unknown()).optional(),
  staging_inventory: z.record(z.unknown()).optional(),
  catering_inventory: z.record(z.unknown()).optional(),
  signage_inventory: z.record(z.unknown()).optional(),
  tech_support_available: z.boolean().optional(),
  setup_staff_available: z.boolean().optional(),
  cleaning_staff_available: z.boolean().optional(),
  security_staff_available: z.boolean().optional(),
  parking_available: z.boolean().optional(),
  storage_space_available: z.boolean().optional(),
  loading_dock_available: z.boolean().optional(),
  catering_kitchen_available: z.boolean().optional(),
  av_control_room_available: z.boolean().optional(),
  breakout_rooms_available: z.boolean().optional(),
  outdoor_space_available: z.boolean().optional(),
  wifi_bandwidth_mbps: z.number().int().optional(),
  internet_connection_type: z.string().optional(),
  network_security_protocols: z.record(z.unknown()).optional(),
  backup_power_available: z.boolean().optional(),
  hvac_system_type: z.string().optional(),
  lighting_system_type: z.string().optional(),
  sound_system_type: z.string().optional(),
  floor_plan_url: z.string().optional(),
  layout_diagrams: z.record(z.unknown()).optional(),
  virtual_tour_url: z.string().optional(),
  seating_chart_url: z.string().optional(),
  stage_dimensions: z.string().optional(),
  dance_floor_dimensions: z.string().optional(),
  ceiling_type: z.string().optional(),
  wall_finish: z.string().optional(),
  flooring_type: z.string().optional(),
  window_treatments: z.string().optional(),
  acoustic_features: z.string().optional(),
  primary_photo_url: z.string().optional(),
  photo_gallery: z.record(z.unknown()).optional(),
  marketing_description: z.string().optional(),
  amenities_description: z.string().optional(),
  unique_selling_points: z.string().optional(),
  noise_restrictions: z.boolean().optional(),
  alcohol_allowed: z.boolean().optional(),
  smoking_allowed: z.boolean().optional(),
  food_restrictions: z.string().optional(),
  decoration_policy: z.string().optional(),
  cancellation_policy: z.string().optional(),
  catering_required: z.boolean().optional(),
  in_house_catering_available: z.boolean().optional(),
  external_catering_allowed: z.boolean().optional(),
  kitchen_access: z.boolean().optional(),
  bar_service_available: z.boolean().optional(),
  dietary_options: z.record(z.unknown()).optional(),
  catering_menu_url: z.string().optional(),
  preferred_caterers: z.record(z.unknown()).optional(),
  beverage_packages: z.record(z.unknown()).optional(),
  catering_pricing_details: z.string().optional(),
  max_catering_capacity: z.number().int().optional(),
  catering_setup_time_minutes: z.number().int().optional(),
  catering_teardown_time_minutes: z.number().int().optional(),
  catering_contact_info: z.record(z.unknown()).optional(),
  power_outlets: z.number().int().optional(),
  network_ports: z.number().int().optional(),
  lighting_zones: z.number().int().optional(),
  voltage: z.string().optional(),
  amp_capacity: z.number().int().optional(),
  av_integration_details: z.string().optional(),
  tech_requirements: z.string().optional(),
  rigging_points: z.number().int().optional(),
  ceiling_load_capacity_kg: z.number().int().optional(),
  ceiling_load_capacity_lbs: z.number().int().optional(),
  stage_rigging_available: z.boolean().optional(),
  lighting_rigging_available: z.boolean().optional(),
  sound_rigging_available: z.boolean().optional(),
  av_rigging_available: z.boolean().optional(),
  special_effects_rigging_available: z.boolean().optional(),
  rigging_contact_info: z.record(z.unknown()).optional(),
  irdb_compliance: z.boolean().optional(),
  tech_support_contact_info: z.record(z.unknown()).optional(),
  emergency_procedures: z.string().optional(),
  safety_certifications: z.record(z.unknown()).optional(),
  fire_safety_equipment: z.record(z.unknown()).optional(),
  security_features: z.record(z.unknown()).optional(),
  emergency_exits: z.number().int().optional(),
  emergency_exit_locations: z.record(z.unknown()).optional(),
  accessibility_features: z.record(z.unknown()).optional(),
  min_advance_booking_hours: z.number().int().optional(),
  max_advance_booking_days: z.number().int().optional(),
  requires_approval: z.boolean().optional(),
  auto_confirm: z.boolean().optional(),
  internal_notes: z.string().optional(),
  guest_facing_notes: z.string().optional(),
  setup_instructions: z.string().optional(),
  teardown_instructions: z.string().optional(),
  special_requirements: z.string().optional(),
  emergency_contact_info: z.record(z.unknown()).optional(),
  vendor_access_instructions: z.string().optional(),
  cleaning_instructions: z.string().optional(),
  maintenance_instructions: z.string().optional(),
  inspection_schedule: z.string().optional(),
  inspection_notes: z.string().optional(),
  regulatory_compliance: z.string().optional(),
  insurance_requirements: z.string().optional(),
  booking_restrictions: z.string().optional(),
  cancellation_fees: z.string().optional(),
  rescheduling_policy: z.string().optional(),
  payment_terms: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date().optional(),
  created_by: uuid.optional(),
  updated_by: uuid.optional(),
  is_deleted: z.boolean().optional(),
  deleted_at: z.coerce.date().optional(),
  deleted_by: uuid.optional(),
  version: z.bigint().optional(),
});

export type MeetingRooms = z.infer<typeof MeetingRoomsSchema>;

/**
 * Schema for creating a new meeting rooms
 */
export const CreateMeetingRoomsSchema = MeetingRoomsSchema.omit({
  // TODO: Add fields to omit for creation
});

export type CreateMeetingRooms = z.infer<typeof CreateMeetingRoomsSchema>;

/**
 * Schema for updating a meeting rooms
 */
export const UpdateMeetingRoomsSchema = MeetingRoomsSchema.partial();

export type UpdateMeetingRooms = z.infer<typeof UpdateMeetingRoomsSchema>;
