/**
 * IncidentReports Schema
 * @table incident_reports
 * @category 05-operations
 * @synchronized 2025-11-03
 */

import { z } from "zod";

import { uuid, money } from "../../shared/base-schemas.js";

/**
 * Complete IncidentReports schema
 */
export const IncidentReportsSchema = z.object({
	incident_id: uuid,
	tenant_id: uuid,
	property_id: uuid,
	incident_number: z.string(),
	incident_title: z.string(),
	incident_type: z.string(),
	incident_category: z.string().optional(),
	incident_subcategory: z.string().optional(),
	severity: z.string(),
	severity_score: z.number().int().optional(),
	incident_date: z.coerce.date(),
	incident_time: z.string(),
	incident_datetime: z.coerce.date(),
	discovered_date: z.coerce.date().optional(),
	discovered_time: z.string().optional(),
	discovered_by: uuid.optional(),
	discovered_by_name: z.string().optional(),
	time_to_discovery_minutes: z.number().int().optional(),
	incident_location: z.string(),
	room_number: z.string().optional(),
	room_id: uuid.optional(),
	floor_number: z.number().int().optional(),
	area_name: z.string().optional(),
	specific_location: z.string().optional(),
	incident_description: z.string(),
	sequence_of_events: z.string().optional(),
	contributing_factors: z.string().optional(),
	root_cause: z.string().optional(),
	guest_involved: z.boolean().optional(),
	guest_id: uuid.optional(),
	guest_name: z.string().optional(),
	guest_room_number: z.string().optional(),
	staff_involved: z.boolean().optional(),
	staff_ids: z.array(uuid).optional(),
	staff_names: z.array(z.string()).optional(),
	third_party_involved: z.boolean().optional(),
	third_party_details: z.string().optional(),
	witness_count: z.number().int().optional(),
	witnesses: z.record(z.unknown()).optional(),
	injuries_sustained: z.boolean().optional(),
	injury_details: z.string().optional(),
	injury_severity: z.string().optional(),
	medical_attention_required: z.boolean().optional(),
	medical_attention_provided: z.boolean().optional(),
	medical_provider: z.string().optional(),
	ambulance_called: z.boolean().optional(),
	hospital_name: z.string().optional(),
	medical_report_number: z.string().optional(),
	fatality_involved: z.boolean().optional(),
	fatality_details: z.string().optional(),
	coroner_notified: z.boolean().optional(),
	property_damage: z.boolean().optional(),
	damage_description: z.string().optional(),
	estimated_damage_cost: money.optional(),
	actual_damage_cost: money.optional(),
	financial_loss: money.optional(),
	insurance_claim_filed: z.boolean().optional(),
	insurance_claim_number: z.string().optional(),
	insurance_company: z.string().optional(),
	claim_amount: money.optional(),
	immediate_actions_taken: z.string(),
	first_responder: uuid.optional(),
	first_responder_name: z.string().optional(),
	emergency_services_called: z.boolean().optional(),
	emergency_service_types: z.array(z.string()).optional(),
	police_notified: z.boolean().optional(),
	police_report_number: z.string().optional(),
	police_department: z.string().optional(),
	officer_name: z.string().optional(),
	officer_badge_number: z.string().optional(),
	police_report_filed: z.boolean().optional(),
	incident_status: z.string().optional(),
	investigation_required: z.boolean().optional(),
	investigation_started: z.boolean().optional(),
	investigation_start_date: z.coerce.date().optional(),
	investigated_by: uuid.optional(),
	investigator_name: z.string().optional(),
	investigation_completed: z.boolean().optional(),
	investigation_completion_date: z.coerce.date().optional(),
	investigation_findings: z.string().optional(),
	investigation_report_url: z.string().optional(),
	follow_up_required: z.boolean().optional(),
	follow_up_actions: z.record(z.unknown()).optional(),
	follow_up_completed: z.boolean().optional(),
	corrective_actions_required: z.boolean().optional(),
	corrective_actions: z.string().optional(),
	preventive_measures: z.string().optional(),
	corrective_actions_implemented: z.boolean().optional(),
	implementation_date: z.coerce.date().optional(),
	implementation_verified: z.boolean().optional(),
	verified_by: uuid.optional(),
	management_notified: z.boolean().optional(),
	management_notified_at: z.coerce.date().optional(),
	management_id: uuid.optional(),
	owner_notified: z.boolean().optional(),
	owner_notified_at: z.coerce.date().optional(),
	corporate_notified: z.boolean().optional(),
	corporate_notified_at: z.coerce.date().optional(),
	regulatory_reporting_required: z.boolean().optional(),
	regulatory_authorities_notified: z.array(z.string()).optional(),
	osha_reportable: z.boolean().optional(),
	osha_report_filed: z.boolean().optional(),
	osha_report_number: z.string().optional(),
	media_attention: z.boolean().optional(),
	media_statement_issued: z.boolean().optional(),
	media_contact: z.string().optional(),
	public_relations_involved: z.boolean().optional(),
	legal_action_taken: z.boolean().optional(),
	legal_case_number: z.string().optional(),
	attorney_assigned: z.string().optional(),
	lawsuit_filed: z.boolean().optional(),
	settlement_reached: z.boolean().optional(),
	settlement_amount: money.optional(),
	photos_taken: z.boolean().optional(),
	photo_count: z.number().int().optional(),
	photo_urls: z.array(z.string()).optional(),
	video_footage_available: z.boolean().optional(),
	video_urls: z.array(z.string()).optional(),
	documents_attached: z.boolean().optional(),
	document_urls: z.array(z.string()).optional(),
	evidence_collected: z.boolean().optional(),
	evidence_description: z.string().optional(),
	evidence_location: z.string().optional(),
	reviewed: z.boolean().optional(),
	reviewed_by: uuid.optional(),
	reviewed_at: z.coerce.date().optional(),
	review_notes: z.string().optional(),
	approved: z.boolean().optional(),
	approved_by: uuid.optional(),
	approved_at: z.coerce.date().optional(),
	closed: z.boolean().optional(),
	closed_by: uuid.optional(),
	closed_at: z.coerce.date().optional(),
	closure_notes: z.string().optional(),
	lessons_learned: z.string().optional(),
	training_required: z.boolean().optional(),
	training_topics: z.array(z.string()).optional(),
	policy_changes_needed: z.boolean().optional(),
	policy_recommendations: z.string().optional(),
	related_incidents: z.array(uuid).optional(),
	is_recurring_incident: z.boolean().optional(),
	previous_similar_incidents: z.number().int().optional(),
	is_confidential: z.boolean().optional(),
	confidentiality_level: z.string().optional(),
	access_restricted_to: z.array(uuid).optional(),
	metadata: z.record(z.unknown()).optional(),
	tags: z.array(z.string()).optional(),
	notes: z.string().optional(),
	created_at: z.coerce.date().optional(),
	updated_at: z.coerce.date().optional(),
	created_by: uuid,
	updated_by: uuid.optional(),
	is_deleted: z.boolean().optional(),
	deleted_at: z.coerce.date().optional(),
	deleted_by: uuid.optional(),
});

export type IncidentReports = z.infer<typeof IncidentReportsSchema>;

/**
 * Schema for creating a new incident reports
 */
export const CreateIncidentReportsSchema = IncidentReportsSchema.omit({
	// TODO: Add fields to omit for creation
});

export type CreateIncidentReports = z.infer<typeof CreateIncidentReportsSchema>;

/**
 * Schema for updating a incident reports
 */
export const UpdateIncidentReportsSchema = IncidentReportsSchema.partial();

export type UpdateIncidentReports = z.infer<typeof UpdateIncidentReportsSchema>;
