-- =====================================================
-- 23_analytics_reports_fk.sql
-- Foreign Key Constraints for analytics_reports table
--
-- Relationships: tenant, property, user
-- =====================================================

\c tartware

-- Drop constraints if they exist (for development)
ALTER TABLE analytics_reports DROP CONSTRAINT IF EXISTS fk_analytics_reports_tenant;
ALTER TABLE analytics_reports DROP CONSTRAINT IF EXISTS fk_analytics_reports_property;
ALTER TABLE analytics_reports DROP CONSTRAINT IF EXISTS fk_analytics_reports_created_by;
ALTER TABLE analytics_reports DROP CONSTRAINT IF EXISTS fk_analytics_reports_updated_by;
ALTER TABLE analytics_reports DROP CONSTRAINT IF EXISTS fk_analytics_reports_generated_by;

-- Tenant reference (required)
ALTER TABLE analytics_reports
    ADD CONSTRAINT fk_analytics_reports_tenant
    FOREIGN KEY (tenant_id)
    REFERENCES tenants(tenant_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_analytics_reports_tenant ON analytics_reports IS 'Reports belong to a tenant';

-- Property reference (optional - may be tenant-wide)
ALTER TABLE analytics_reports
    ADD CONSTRAINT fk_analytics_reports_property
    FOREIGN KEY (property_id)
    REFERENCES properties(property_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_analytics_reports_property ON analytics_reports IS 'Reports may be property-specific';

-- Created by user
ALTER TABLE analytics_reports
    ADD CONSTRAINT fk_analytics_reports_created_by
    FOREIGN KEY (created_by)
    REFERENCES users(user_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- Updated by user
ALTER TABLE analytics_reports
    ADD CONSTRAINT fk_analytics_reports_updated_by
    FOREIGN KEY (updated_by)
    REFERENCES users(user_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- Generated by user
ALTER TABLE analytics_reports
    ADD CONSTRAINT fk_analytics_reports_generated_by
    FOREIGN KEY (generated_by)
    REFERENCES users(user_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_analytics_reports_generated_by ON analytics_reports IS 'User who generated this report instance';

-- Success message
\echo '✓ Constraints created: analytics_reports (23/37)'
\echo '  - 5 foreign key constraints'
\echo ''
