-- =====================================================
-- 25_command_batches.sql
-- Batch command results (WS-04)
-- One row per batch run, one row per target inside it.
--
-- Why this exists: a batch command is accepted with 202 and
-- runs asynchronously, so its per-item outcomes have nowhere
-- to be returned to. Before this table `group.check_in` built
-- a rich per-reservation summary and threw it away — the
-- consumer discards handler return values. An operator who
-- mass-cancels 200 bookings needs to know which of them did
-- not cancel, and needs it after the request has ended.
-- Date: 2026-08-28
-- =====================================================

\c tartware \echo 'Creating command batch result tables...'

CREATE TABLE IF NOT EXISTS command_batches (
    batch_id UUID PRIMARY KEY,                                                   -- Client-supplied or generated; replays report against the same row
    tenant_id UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,           -- Owning tenant (RLS-scoped)
    property_id UUID,                                                            -- Property the batch acted on, when scoped to one
    command_name VARCHAR(150) NOT NULL,                                          -- Batch command that produced this run
    status command_batch_status NOT NULL DEFAULT 'RUNNING',                      -- Run lifecycle status
    total INTEGER NOT NULL DEFAULT 0,                                            -- Items requested
    succeeded INTEGER NOT NULL DEFAULT 0,                                        -- Items applied
    failed INTEGER NOT NULL DEFAULT 0,                                           -- Items the handler refused
    skipped INTEGER NOT NULL DEFAULT 0,                                          -- Items never attempted (dry run, or stopped early)
    dry_run BOOLEAN NOT NULL DEFAULT FALSE,                                      -- Run resolved and reported without changing anything
    correlation_id VARCHAR(120),                                                 -- Distributed tracing correlation ID
    actor_id UUID,                                                               -- Actor who initiated the batch
    error_code VARCHAR(100),                                                     -- Set when the run itself failed before/while iterating
    error_message TEXT,                                                          -- Human-readable detail for error_code
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,                                 -- Arbitrary extension metadata
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),                               -- Run start timestamp
    completed_at TIMESTAMPTZ,                                                    -- Run completion timestamp (NULL while RUNNING)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),                               -- Row creation timestamp
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),                               -- Row last-update timestamp
    CONSTRAINT command_batches_counts_account_for_every_item
        CHECK (succeeded + failed + skipped <= total)
);

COMMENT ON TABLE command_batches IS 'One row per batch command run. Holds the aggregate an async batch cannot return to its caller.';
COMMENT ON COLUMN command_batches.batch_id IS 'Client-supplied batch id (idempotent replay) or generated by the runner';
COMMENT ON COLUMN command_batches.status IS 'RUNNING, COMPLETED, PARTIAL, FAILED';
COMMENT ON COLUMN command_batches.dry_run IS 'When true the run changed nothing; every item is SKIPPED';
COMMENT ON COLUMN command_batches.error_code IS 'Set only when the run itself failed (bad reason code, unknown property) rather than an individual item';
COMMENT ON CONSTRAINT command_batches_counts_account_for_every_item ON command_batches IS 'Outcomes never exceed the item count; equality holds once status leaves RUNNING';

CREATE INDEX IF NOT EXISTS idx_command_batches_tenant_command
    ON command_batches (tenant_id, command_name, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_command_batches_property
    ON command_batches (tenant_id, property_id, started_at DESC)
    WHERE property_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS command_batch_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),                                          -- Unique item result identifier
    batch_id UUID NOT NULL REFERENCES command_batches (batch_id) ON DELETE CASCADE,          -- Owning batch run
    tenant_id UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,                       -- Owning tenant (RLS-scoped; denormalised so the policy reaches item rows directly)
    item_index INTEGER NOT NULL,                                                             -- Position in the request array — ties a result to what was asked for
    target_id UUID,                                                                          -- Entity acted on; NULL when the item was rejected before a target resolved
    outcome command_batch_item_outcome NOT NULL,                                             -- SUCCEEDED, FAILED or SKIPPED
    event_id UUID,                                                                           -- Event the successful item enqueued, for tracing it downstream
    error_code VARCHAR(100),                                                                 -- CommandError.code from the refusal
    error_message TEXT,                                                                      -- Human-readable detail for error_code
    duration_ms INTEGER,                                                                     -- Wall time the item took
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,                                             -- Arbitrary extension metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),                                           -- Row creation timestamp
    CONSTRAINT command_batch_items_failure_carries_a_code
        CHECK (outcome <> 'FAILED' OR error_code IS NOT NULL)
);

COMMENT ON TABLE command_batch_items IS 'Per-target outcome of a batch command run. One row per requested item, always.';
COMMENT ON COLUMN command_batch_items.item_index IS 'Zero-based position in the request items array';
COMMENT ON COLUMN command_batch_items.outcome IS 'SUCCEEDED (applied), FAILED (handler refused), SKIPPED (never attempted)';
COMMENT ON COLUMN command_batch_items.target_id IS 'Entity the item acted on; NULL when the item never resolved to one';
COMMENT ON CONSTRAINT command_batch_items_failure_carries_a_code ON command_batch_items IS 'A failure without a machine-readable code is not actionable, so the database refuses one';

CREATE UNIQUE INDEX IF NOT EXISTS idx_command_batch_items_position
    ON command_batch_items (batch_id, item_index);

CREATE INDEX IF NOT EXISTS idx_command_batch_items_failures
    ON command_batch_items (batch_id, outcome)
    WHERE outcome = 'FAILED';

CREATE INDEX IF NOT EXISTS idx_command_batch_items_target
    ON command_batch_items (tenant_id, target_id)
    WHERE target_id IS NOT NULL;
