/** Common IANA timezones grouped by region for property setup */
export const COMMON_TIMEZONES: ReadonlyArray<{ value: string; label: string }> = [
	// Americas
	{ value: "America/New_York", label: "Eastern Time (US) — UTC−5" },
	{ value: "America/Chicago", label: "Central Time (US) — UTC−6" },
	{ value: "America/Denver", label: "Mountain Time (US) — UTC−7" },
	{ value: "America/Los_Angeles", label: "Pacific Time (US) — UTC−8" },
	{ value: "America/Anchorage", label: "Alaska — UTC−9" },
	{ value: "Pacific/Honolulu", label: "Hawaii — UTC−10" },
	{ value: "America/Toronto", label: "Toronto — UTC−5" },
	{ value: "America/Vancouver", label: "Vancouver — UTC−8" },
	{ value: "America/Mexico_City", label: "Mexico City — UTC−6" },
	{ value: "America/Sao_Paulo", label: "São Paulo — UTC−3" },
	{ value: "America/Argentina/Buenos_Aires", label: "Buenos Aires — UTC−3" },
	{ value: "America/Bogota", label: "Bogotá — UTC−5" },
	{ value: "America/Lima", label: "Lima — UTC−5" },
	{ value: "America/Santiago", label: "Santiago — UTC−4" },

	// Europe
	{ value: "Europe/London", label: "London — UTC+0" },
	{ value: "Europe/Paris", label: "Paris — UTC+1" },
	{ value: "Europe/Berlin", label: "Berlin — UTC+1" },
	{ value: "Europe/Madrid", label: "Madrid — UTC+1" },
	{ value: "Europe/Rome", label: "Rome — UTC+1" },
	{ value: "Europe/Amsterdam", label: "Amsterdam — UTC+1" },
	{ value: "Europe/Zurich", label: "Zurich — UTC+1" },
	{ value: "Europe/Vienna", label: "Vienna — UTC+1" },
	{ value: "Europe/Stockholm", label: "Stockholm — UTC+1" },
	{ value: "Europe/Athens", label: "Athens — UTC+2" },
	{ value: "Europe/Helsinki", label: "Helsinki — UTC+2" },
	{ value: "Europe/Istanbul", label: "Istanbul — UTC+3" },
	{ value: "Europe/Moscow", label: "Moscow — UTC+3" },

	// Asia & Middle East
	{ value: "Asia/Dubai", label: "Dubai — UTC+4" },
	{ value: "Asia/Kolkata", label: "India (IST) — UTC+5:30" },
	{ value: "Asia/Colombo", label: "Sri Lanka — UTC+5:30" },
	{ value: "Asia/Bangkok", label: "Bangkok — UTC+7" },
	{ value: "Asia/Singapore", label: "Singapore — UTC+8" },
	{ value: "Asia/Hong_Kong", label: "Hong Kong — UTC+8" },
	{ value: "Asia/Shanghai", label: "Shanghai — UTC+8" },
	{ value: "Asia/Taipei", label: "Taipei — UTC+8" },
	{ value: "Asia/Seoul", label: "Seoul — UTC+9" },
	{ value: "Asia/Tokyo", label: "Tokyo — UTC+9" },
	{ value: "Asia/Jakarta", label: "Jakarta — UTC+7" },

	// Oceania
	{ value: "Australia/Sydney", label: "Sydney — UTC+10" },
	{ value: "Australia/Melbourne", label: "Melbourne — UTC+10" },
	{ value: "Australia/Perth", label: "Perth — UTC+8" },
	{ value: "Pacific/Auckland", label: "Auckland — UTC+12" },
	{ value: "Pacific/Fiji", label: "Fiji — UTC+12" },

	// Africa
	{ value: "Africa/Cairo", label: "Cairo — UTC+2" },
	{ value: "Africa/Johannesburg", label: "Johannesburg — UTC+2" },
	{ value: "Africa/Nairobi", label: "Nairobi — UTC+3" },
	{ value: "Africa/Lagos", label: "Lagos — UTC+1" },
	{ value: "Africa/Casablanca", label: "Casablanca — UTC+1" },

	// UTC
	{ value: "UTC", label: "UTC — UTC+0" },
];

/** Common ISO 4217 currencies used in hospitality */
export const COMMON_CURRENCIES: ReadonlyArray<{ code: string; name: string; symbol: string }> = [
	{ code: "USD", name: "US Dollar", symbol: "$" },
	{ code: "EUR", name: "Euro", symbol: "€" },
	{ code: "GBP", name: "British Pound", symbol: "£" },
	{ code: "JPY", name: "Japanese Yen", symbol: "¥" },
	{ code: "CHF", name: "Swiss Franc", symbol: "CHF" },
	{ code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
	{ code: "AUD", name: "Australian Dollar", symbol: "A$" },
	{ code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
	{ code: "CNY", name: "Chinese Yuan", symbol: "¥" },
	{ code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
	{ code: "SGD", name: "Singapore Dollar", symbol: "S$" },
	{ code: "KRW", name: "South Korean Won", symbol: "₩" },
	{ code: "INR", name: "Indian Rupee", symbol: "₹" },
	{ code: "THB", name: "Thai Baht", symbol: "฿" },
	{ code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
	{ code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
	{ code: "PHP", name: "Philippine Peso", symbol: "₱" },
	{ code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
	{ code: "BRL", name: "Brazilian Real", symbol: "R$" },
	{ code: "MXN", name: "Mexican Peso", symbol: "MX$" },
	{ code: "ARS", name: "Argentine Peso", symbol: "AR$" },
	{ code: "COP", name: "Colombian Peso", symbol: "COL$" },
	{ code: "CLP", name: "Chilean Peso", symbol: "CLP$" },
	{ code: "AED", name: "UAE Dirham", symbol: "د.إ" },
	{ code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
	{ code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
	{ code: "ZAR", name: "South African Rand", symbol: "R" },
	{ code: "EGP", name: "Egyptian Pound", symbol: "E£" },
	{ code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
	{ code: "NGN", name: "Nigerian Naira", symbol: "₦" },
	{ code: "TRY", name: "Turkish Lira", symbol: "₺" },
	{ code: "RUB", name: "Russian Ruble", symbol: "₽" },
	{ code: "SEK", name: "Swedish Krona", symbol: "kr" },
	{ code: "NOK", name: "Norwegian Krone", symbol: "kr" },
	{ code: "DKK", name: "Danish Krone", symbol: "kr" },
	{ code: "PLN", name: "Polish Zloty", symbol: "zł" },
	{ code: "CZK", name: "Czech Koruna", symbol: "Kč" },
	{ code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
	{ code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
];

/** Common BCP 47 languages for hospitality */
export const COMMON_LANGUAGES: ReadonlyArray<{ code: string; name: string }> = [
	{ code: "en", name: "English" },
	{ code: "es", name: "Español" },
	{ code: "fr", name: "Français" },
	{ code: "de", name: "Deutsch" },
	{ code: "it", name: "Italiano" },
	{ code: "pt", name: "Português" },
	{ code: "nl", name: "Nederlands" },
	{ code: "sv", name: "Svenska" },
	{ code: "da", name: "Dansk" },
	{ code: "no", name: "Norsk" },
	{ code: "fi", name: "Suomi" },
	{ code: "pl", name: "Polski" },
	{ code: "cs", name: "Čeština" },
	{ code: "hu", name: "Magyar" },
	{ code: "el", name: "Ελληνικά" },
	{ code: "tr", name: "Türkçe" },
	{ code: "ru", name: "Русский" },
	{ code: "ar", name: "العربية" },
	{ code: "zh", name: "中文" },
	{ code: "ja", name: "日本語" },
	{ code: "ko", name: "한국어" },
	{ code: "th", name: "ไทย" },
	{ code: "vi", name: "Tiếng Việt" },
	{ code: "id", name: "Bahasa Indonesia" },
	{ code: "ms", name: "Bahasa Melayu" },
	{ code: "hi", name: "हिन्दी" },
	{ code: "ta", name: "தமிழ்" },
	{ code: "si", name: "සිංහල" },
];
