-- =====================================================
-- 69_payment_tokens.sql
-- PCI Token Vault Reference Table
--
-- Purpose: Store references to vaulted payment tokens generated by
--          PCI-compliant gateways (Stripe, Adyen, Shift4, etc.).
-- =====================================================

\c tartware

\echo 'Creating payment_tokens table...'

CREATE TABLE IF NOT EXISTS payment_tokens (
    -- Primary Key
    payment_token_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Multi-Tenancy
    tenant_id UUID NOT NULL,
    property_id UUID,

    -- Guest / Account Association
    guest_id UUID,
    company_id UUID,

    -- Token Details
    token_reference VARCHAR(255) NOT NULL,
    vault_provider VARCHAR(50) NOT NULL CHECK (vault_provider IN ('STRIPE', 'ADYEN', 'SHIFT4', 'HEARTLAND', 'AUTHORIZE_NET', 'BRAINTREE', 'OTHER')),
    payment_network VARCHAR(20) CHECK (payment_network IN ('VISA', 'MASTERCARD', 'AMEX', 'DISCOVER', 'JCB', 'UNIONPAY', 'MAESTRO', 'OTHER')),
    masked_card_number VARCHAR(25) NOT NULL, -- e.g., **** **** **** 1234
    card_expiry_month CHAR(2),
    card_expiry_year CHAR(4),
    cardholder_name VARCHAR(255),
    billing_address JSONB,

    -- Token Capabilities
    supports_recurring BOOLEAN DEFAULT TRUE,
    supports_incidental BOOLEAN DEFAULT FALSE,
    supports_card_on_file BOOLEAN DEFAULT TRUE,
    three_ds_enrolled BOOLEAN DEFAULT FALSE,
    network_token BOOLEAN DEFAULT FALSE,

    -- Status & Metadata
    token_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (token_status IN ('ACTIVE', 'INACTIVE', 'EXPIRED', 'REVOKED')),
    last_used_at TIMESTAMP,
    last_four CHAR(4),
    fingerprint VARCHAR(100),
    metadata JSONB DEFAULT '{}'::jsonb,

    -- Audit
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_at TIMESTAMP,
    updated_by UUID,

    -- Soft Delete
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,
    deleted_by UUID,

    -- Constraints
    CONSTRAINT uq_payment_token UNIQUE (tenant_id, token_reference, vault_provider)
);

COMMENT ON TABLE payment_tokens IS 'References to vaulted PCI-compliant payment tokens.';
COMMENT ON COLUMN payment_tokens.token_reference IS 'Opaque token returned by the payment gateway.';
COMMENT ON COLUMN payment_tokens.masked_card_number IS 'Masked primary account number (no full PAN stored).';
COMMENT ON COLUMN payment_tokens.network_token IS 'TRUE if token is a network token (Visa MT, MasterCard MDES, etc.).';

\echo '✓ Table created: payment_tokens'
