-- =====================================================
-- alert_rules.sql
-- Alert rules configuration for automatic alert generation
-- =====================================================

\c tartware

\echo 'Creating alert_rules table...'

CREATE TABLE IF NOT EXISTS alert_rules (
    -- Primary Key
    rule_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Rule Identification
    rule_name VARCHAR(100) NOT NULL UNIQUE,

    -- Metric Configuration
    metric_query TEXT NOT NULL,

    -- Condition Configuration
    condition_type VARCHAR(50) NOT NULL, -- 'threshold', 'deviation', 'trend'
    threshold_value NUMERIC,
    deviation_percent NUMERIC,
    time_window INTERVAL,

    -- Alert Configuration
    severity VARCHAR(20) DEFAULT 'WARNING',
    is_active BOOLEAN DEFAULT true,

    -- Notification Configuration
    notification_channels TEXT[],

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT chk_condition_type CHECK (condition_type IN ('threshold', 'deviation', 'trend', 'spike')),
    CONSTRAINT chk_rule_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

COMMENT ON TABLE alert_rules IS
'Defines rules for automatic alert generation';

COMMENT ON COLUMN alert_rules.rule_id IS 'Unique identifier for the alert rule';
COMMENT ON COLUMN alert_rules.rule_name IS 'Human-readable name identifying the rule';
COMMENT ON COLUMN alert_rules.metric_query IS 'SQL or expression used to evaluate the metric';
COMMENT ON COLUMN alert_rules.condition_type IS 'Evaluation strategy: threshold, deviation, trend, or spike';
COMMENT ON COLUMN alert_rules.threshold_value IS 'Absolute value that triggers the alert when using threshold condition';
COMMENT ON COLUMN alert_rules.deviation_percent IS 'Percentage deviation from baseline that triggers the alert';
COMMENT ON COLUMN alert_rules.time_window IS 'Lookback interval over which the metric is evaluated';
COMMENT ON COLUMN alert_rules.severity IS 'Default severity assigned to alerts generated by this rule';
COMMENT ON COLUMN alert_rules.is_active IS 'Whether this rule is currently enabled';
COMMENT ON COLUMN alert_rules.notification_channels IS 'Channels to notify when this rule fires (email, SMS, webhook)';

\echo '✓ alert_rules created.'
