/**
 * validate-openapi.mjs
 *
 * Post-export validation of OpenAPI specs generated by export-openapi.mjs.
 * Checks:
 *   1. Every exported JSON file is valid OpenAPI 3.x (structural parse).
 *   2. Reports routes whose response schema is the open `{ type: "object", additionalProperties: true }`
 *      placeholder (jsonObjectSchema) — these are not machine-usable for SDK generation.
 *   3. Exits with code 1 only on structural errors. Open-schema warnings are surfaced
 *      as annotations but do NOT fail CI (yet). Set OPENAPI_STRICT=1 to fail on warnings too.
 *
 * Usage:
 *   node scripts/validate-openapi.mjs              # validate docs/openapi/*.json
 *   OPENAPI_STRICT=1 node scripts/validate-openapi.mjs  # also fail on open-schema routes
 */

import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const workspaceRoot = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const specsDir = path.resolve(workspaceRoot, "docs/openapi");
const strict = process.env.OPENAPI_STRICT === "1";

/**
 * Detect the open "jsonObjectSchema" placeholder.
 * Matches `{ "type": "object", "additionalProperties": true }` with no `properties` key.
 */
const isOpenSchema = (schema) => {
  if (!schema || typeof schema !== "object") return false;
  return (
    schema.type === "object" &&
    schema.additionalProperties === true &&
    !schema.properties
  );
};

/**
 * Walk a spec's paths and report response schemas that are open objects.
 * Returns an array of { method, path, statusCode } entries.
 */
const findOpenSchemaRoutes = (spec) => {
  const findings = [];
  const paths = spec.paths ?? {};
  for (const [routePath, methods] of Object.entries(paths)) {
    for (const [method, operation] of Object.entries(methods)) {
      if (typeof operation !== "object" || !operation.responses) continue;
      for (const [statusCode, response] of Object.entries(operation.responses)) {
        const content = response?.content;
        if (!content) continue;
        for (const mediaType of Object.values(content)) {
          if (isOpenSchema(mediaType?.schema)) {
            findings.push({
              method: method.toUpperCase(),
              path: routePath,
              statusCode,
            });
          }
        }
      }
    }
  }
  return findings;
};

const run = async () => {
  let files;
  try {
    files = (await readdir(specsDir)).filter((f) => f.endsWith(".json"));
  } catch {
    console.error(`[validate:openapi] No specs found in ${specsDir}. Run "pnpm run export:openapi" first.`);
    process.exitCode = 1;
    return;
  }

  if (files.length === 0) {
    console.error("[validate:openapi] No .json spec files found.");
    process.exitCode = 1;
    return;
  }

  let structuralErrors = 0;
  let totalOpenSchemaRoutes = 0;
  const summaryByService = [];

  for (const file of files) {
    const filePath = path.join(specsDir, file);
    const raw = await readFile(filePath, "utf8");

    // 1. Structural validity
    let spec;
    try {
      spec = JSON.parse(raw);
    } catch (err) {
      console.error(`[validate:openapi] FAIL ${file}: invalid JSON — ${err.message}`);
      structuralErrors++;
      continue;
    }

    if (!spec.openapi && !spec.swagger) {
      console.error(`[validate:openapi] FAIL ${file}: missing openapi/swagger version field`);
      structuralErrors++;
      continue;
    }

    if (!spec.paths || Object.keys(spec.paths).length === 0) {
      console.warn(`[validate:openapi] WARN ${file}: no paths defined`);
    }

    // 2. Count total routes
    let routeCount = 0;
    for (const methods of Object.values(spec.paths ?? {})) {
      for (const key of Object.keys(methods)) {
        if (["get", "post", "put", "patch", "delete", "options", "head"].includes(key)) {
          routeCount++;
        }
      }
    }

    // 3. Open-schema detection
    const openRoutes = findOpenSchemaRoutes(spec);
    totalOpenSchemaRoutes += openRoutes.length;

    const serviceName = file.replace(".json", "");
    const typedRoutes = routeCount - openRoutes.length;
    const coverage = routeCount > 0 ? ((typedRoutes / routeCount) * 100).toFixed(1) : "N/A";

    summaryByService.push({
      service: serviceName,
      routes: routeCount,
      typed: typedRoutes,
      open: openRoutes.length,
      coverage: `${coverage}%`,
    });

    if (openRoutes.length > 0) {
      console.warn(
        `[validate:openapi] WARN ${serviceName}: ${openRoutes.length}/${routeCount} routes use open schema (jsonObjectSchema)`,
      );
      for (const r of openRoutes) {
        console.warn(`  ${r.method} ${r.path} → ${r.statusCode}`);
      }
    } else {
      console.log(`[validate:openapi] OK   ${serviceName}: ${routeCount} routes, all typed`);
    }
  }

  // Summary table
  console.log("\n=== OpenAPI Schema Coverage ===");
  console.table(summaryByService);
  console.log(
    `Total: ${totalOpenSchemaRoutes} open-schema response(s) across ${files.length} spec(s)`,
  );

  if (structuralErrors > 0) {
    console.error(`\n[validate:openapi] ${structuralErrors} spec(s) have structural errors`);
    process.exitCode = 1;
  }

  if (strict && totalOpenSchemaRoutes > 0) {
    console.error(
      `\n[validate:openapi] OPENAPI_STRICT=1: ${totalOpenSchemaRoutes} routes have untyped response schemas`,
    );
    process.exitCode = 1;
  }
};

run().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : error);
  process.exitCode = 1;
});
