export const GET_UI_PREFERENCES_SQL = `
  SELECT
    preference_id,
    tenant_id,
    user_id,
    theme,
    language,
    timezone,
    date_format,
    time_format,
    currency_display,
    home_page,
    home_page_dashboard_layout,
    default_page_size,
    default_sort_field,
    default_sort_direction,
    notification_sound_enabled,
    notification_desktop_enabled,
    notification_email_digest,
    pinned_reports,
    recent_searches,
    favorite_properties,
    profile_display_fields,
    profile_history_display,
    default_profile_tab,
    created_at,
    updated_at
  FROM user_ui_preferences
  WHERE user_id = $1::uuid
    AND tenant_id = $2::uuid
  LIMIT 1
`;

export const UPSERT_UI_PREFERENCES_SQL = `
  INSERT INTO user_ui_preferences (
    tenant_id,
    user_id,
    theme,
    language,
    timezone,
    date_format,
    time_format,
    currency_display,
    home_page,
    home_page_dashboard_layout,
    default_page_size,
    default_sort_field,
    default_sort_direction,
    notification_sound_enabled,
    notification_desktop_enabled,
    notification_email_digest,
    pinned_reports,
    recent_searches,
    favorite_properties,
    profile_display_fields,
    profile_history_display,
    default_profile_tab,
    created_by,
    updated_by
  ) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $2, $2
  )
  ON CONFLICT (tenant_id, user_id) DO UPDATE SET
    theme = COALESCE(EXCLUDED.theme, user_ui_preferences.theme),
    language = COALESCE(EXCLUDED.language, user_ui_preferences.language),
    timezone = COALESCE(EXCLUDED.timezone, user_ui_preferences.timezone),
    date_format = COALESCE(EXCLUDED.date_format, user_ui_preferences.date_format),
    time_format = COALESCE(EXCLUDED.time_format, user_ui_preferences.time_format),
    currency_display = COALESCE(EXCLUDED.currency_display, user_ui_preferences.currency_display),
    home_page = COALESCE(EXCLUDED.home_page, user_ui_preferences.home_page),
    home_page_dashboard_layout = COALESCE(EXCLUDED.home_page_dashboard_layout, user_ui_preferences.home_page_dashboard_layout),
    default_page_size = COALESCE(EXCLUDED.default_page_size, user_ui_preferences.default_page_size),
    default_sort_field = COALESCE(EXCLUDED.default_sort_field, user_ui_preferences.default_sort_field),
    default_sort_direction = COALESCE(EXCLUDED.default_sort_direction, user_ui_preferences.default_sort_direction),
    notification_sound_enabled = COALESCE(EXCLUDED.notification_sound_enabled, user_ui_preferences.notification_sound_enabled),
    notification_desktop_enabled = COALESCE(EXCLUDED.notification_desktop_enabled, user_ui_preferences.notification_desktop_enabled),
    notification_email_digest = COALESCE(EXCLUDED.notification_email_digest, user_ui_preferences.notification_email_digest),
    pinned_reports = COALESCE(EXCLUDED.pinned_reports, user_ui_preferences.pinned_reports),
    recent_searches = COALESCE(EXCLUDED.recent_searches, user_ui_preferences.recent_searches),
    favorite_properties = COALESCE(EXCLUDED.favorite_properties, user_ui_preferences.favorite_properties),
    profile_display_fields = COALESCE(EXCLUDED.profile_display_fields, user_ui_preferences.profile_display_fields),
    profile_history_display = COALESCE(EXCLUDED.profile_history_display, user_ui_preferences.profile_history_display),
    default_profile_tab = COALESCE(EXCLUDED.default_profile_tab, user_ui_preferences.default_profile_tab),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $2
  RETURNING
    preference_id,
    tenant_id,
    user_id,
    theme,
    language,
    timezone,
    date_format,
    time_format,
    currency_display,
    home_page,
    home_page_dashboard_layout,
    default_page_size,
    default_sort_field,
    default_sort_direction,
    notification_sound_enabled,
    notification_desktop_enabled,
    notification_email_digest,
    pinned_reports,
    recent_searches,
    favorite_properties,
    profile_display_fields,
    profile_history_display,
    default_profile_tab,
    created_at,
    updated_at
`;
