/**
 * DEV DOC
 * Module: schemas/07-analytics/night-audit-checkpoints.ts
 * Description: NightAuditCheckpoints Schema — per-step completion record for each night audit run
 * Table: night_audit_checkpoints
 * Category: 07-analytics
 * Primary exports: NightAuditCheckpointsSchema, CreateNightAuditCheckpointsSchema
 * @table night_audit_checkpoints
 * @category 07-analytics
 * Ownership: Schema package
 */

import { z } from "zod";

import { uuid } from "../../shared/base-schemas.js";

/**
 * Step status values for a night audit checkpoint.
 * COMPLETED = step ran and produced records.
 * SKIPPED   = step was disabled by command flag (e.g. post_room_charges=false).
 * FAILED    = step threw an error; written outside the main TX so it survives rollback.
 */
export const NightAuditCheckpointStatusEnum = z.enum(["COMPLETED", "SKIPPED", "FAILED"]);
export type NightAuditCheckpointStatus = z.infer<typeof NightAuditCheckpointStatusEnum>;

/**
 * Complete NightAuditCheckpoints schema — aligned with night_audit_checkpoints table.
 * COMPLETED/SKIPPED rows are written inside the main audit transaction so they
 * commit or roll back atomically with the charge_postings they describe.
 * FAILED rows are written outside the transaction (in the catch path) so they
 * survive a rollback and are available for recovery/diagnostics.
 */
export const NightAuditCheckpointsSchema = z.object({
	checkpoint_id: uuid,
	tenant_id: uuid,
	property_id: uuid,
	/** Matches night_audit_log.audit_run_id — groups all steps of one run. */
	audit_run_id: uuid,
	/** Step number: 2=room-charges, 3=packages, 4=ota-commissions, 5=no-shows. */
	step_number: z.number().int().min(1),
	/** Human-readable step name for tooling / support queries. */
	step_name: z.string().max(100),
	status: NightAuditCheckpointStatusEnum,
	/** Number of reservations / items processed by this step. */
	records_processed: z.number().int().default(0),
	started_at: z.coerce.date(),
	completed_at: z.coerce.date().optional(),
	created_by: uuid.optional(),
});

export type NightAuditCheckpoints = z.infer<typeof NightAuditCheckpointsSchema>;

/**
 * Schema for inserting a new checkpoint row.
 * checkpoint_id is generated by the DB (uuid_generate_v4 default).
 */
export const CreateNightAuditCheckpointsSchema = NightAuditCheckpointsSchema.omit({
	checkpoint_id: true,
	started_at: true,
	completed_at: true,
});

export type CreateNightAuditCheckpoints = z.infer<typeof CreateNightAuditCheckpointsSchema>;
