theme: jekyll-theme-cayman
title: Tartware PMS Documentation
description: Enterprise-Grade Property Management System - Industry Standards Compliant
show_downloads: false
google_analytics:

# Navigation
navigation:
  - title: Home
    url: /
  - title: Industry Standards
    url: /industry-standards
  - title: Database Architecture
    url: /database-architecture
  - title: Multi-Tenancy
    url: /multi-tenancy
  - title: GitHub
    url: https://github.com/red2n/tartware

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
twitter:
  username:
  card: summary

logo:

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
